version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis-data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  postgres:
    image: postgres
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  websocket:
    image: websocket_img
    restart: always
    container_name: ${WEBSOCKET_CONTAINER_NAME}
    environment:
      IM_CONTAINER: true
    ports:
      - "${WEBSOCKET_API_PORT}:3001"
      - "${WEBSOCKET_PORT}:8080"
    depends_on:
      - redis
      - postgres

  api:
    image: api_img
    restart: always
    container_name: ${API_CONTAINER_NAME}
    environment:
      IM_CONTAINER: true
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - redis
      - postgres
      - websocket
