# FROM node:lts-stretch-slim
FROM node:alpine
WORKDIR /usr/src/app
COPY . .
RUN npm install --location=global typescript
RUN npm install --location=global ts-node
RUN npm install
CMD ["ts-node", "src/api.ts"]   